import h from 'virtual-dom/h';

function adanaLink() {
  return h('a', {
    href: 'https://github.com/adana-coverage'
  }, ['Adana']);
}

export default function footer({timestamp}) {
  return h('div', {
    className: 'footer'
  }, [
    'Generated by ',
    adanaLink(),
    ` on ${new Date(timestamp)}`
  ]);
}
